var agenda = [];
agenda [0] = "Jorge";
console.table(agenda);
agenda [1] = "Jose";
console.table(agenda);
agenda [2] = "Pepe";
console.table(agenda);
agenda.push("Maria");
console.table(agenda);
agenda.pop();
console.table(agenda);
agenda.splice(1,2);
console.table(agenda);